name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build .--file Dockerfile --tag ghcr.io/sarabudeanu/myfirstdjangoapp:latest
    - name: Login on GHCR
      run: docker login ghcr.io -u sarabudeanu -p ${GHCR_TOKEN}
    - name: Push the Docker image to GHCR
      run: docker push ghcr.io/sarabudeanu/myfirstdjangoapp:latest
